### ISSUE TITLE
offset error

### ISSUE THREAD

**Issue by typometre** [ltrgoddard/inliner#1]
when trying the script, I got the following error.
but I am so incapable that I don't know which i could do.

```
File "inliner.py", line 45, in <module>
    note = "^[" + text[refStart+offset:len(text)-1] + "]"
NameError: name 'offset' is not defined
```

**Comment by ltrgoddard** [comment]
It's most likely that your input document doesn't contain any footnotes formatted in the style used by Pandoc's Markdown writer (e.g. "[^23]: This is a footnote." at the end of the document). I've just updated the script to make it a bit less rough-and-ready: try it again (using Python 3) and you should get a message saying "0 notes replaced".

**Comment by typometre** [comment]
Thanks for the reply.
I must be silly but Nothing is found in this sample text.

```
# inliner

*Usage*: python inliner.py [input.markdown] [output.markdown]

This essay [has] two broad intentions.[^1] This is some text.


[^1]: The essay was originally presented as a paper at the first Information Design Conference, held at Cranfield, England in December 1984. The author is grateful to the editors of Design Issues for their criticisms of an earlier draft. In the text now published it seemed appropriate to the aims and content of the paper to retain as much as possible of its original colloquial manner.

This is a statement that should[^Hello] be attributed to its source.


A Python script to convert reference-style Markdown endnotes ^[as generated by Pandoc's Markdown writer] at the end of the document to Pandoc's inline footnotes ("this is some text^[this is a footnote]"). Works on documents with 99,999 or fewer notes; if that's not enough for you, you've got bigger problems than footnote formatting.
```

You told about Python 3. It seems I only have Python 2.7 from the Mac system. Is this could be the reason?

**Comment by ltrgoddard** [comment]
Ah, the issue with that sample text is that the document must have
multiple, sequentially-numbered notes at the end of the document. The
script finds the end of each note by looking for the next note number, so
if there's only one note then there's nothing to find for the 'nextRef'
variable. It's a bit of a hacky way to implement it, but it's only supposed
to be a single-use script. Try it again with a document generated by
Pandoc's Markdown writer and let me know if there are any further issues.
It should run fine on Python 2.x, actually.

**Comment by typometre** [comment]
Yeah, with two numbered references style footnote, it works. 
Found it really useful even though I don't use it with Pandoc so I must stick to write footnote reliably.
Thanks.

**Comment by ltrgoddard** [comment]
No problem!
